### ISSUE TITLE
phan.analyzedProjectDirectory = './'?

### ISSUE THREAD

**Issue by kenjiuno** [TysonAndre/vscode-php-phan#45]
I want specify project root as a relative path in `.vscode\settings.json`

```json
{
    "phan.analyzedProjectDirectory": "./"
}
```

However it seems to be invalid for me:

![image](https://user-images.githubusercontent.com/5955540/50721537-7317ed00-1104-11e9-952f-9c6807e70597.png)

**Comment by TysonAndre** [comment]
Phan doesn't support relative paths for that setting. There's also a question of **what** it would be relative to (the workspace folder would make the most sense). `./some-subdir` would make sense in some projects, but not all projects

You can provide either an absolute path, or an array of absolute paths.

The syntax would probably be different if Phan ever supported automatically analyzing the current workspace. See https://github.com/TysonAndre/vscode-php-phan/issues/29 for the ticket to support that.
