### ISSUE TITLE
Allow to configure analysis to occur on save instead of during typing

### ISSUE THREAD

**Issue by adduc** [TysonAndre/vscode-php-phan#6]
Phan can be a bit CPU-intensive (particularly when plugins are involved). It would be nice if the extension could be configured to invoke Phan on save instead of during typing.

**Comment by TysonAndre** [comment]
```javascript
const disposable = new LanguageClient('Phan Language Server', serverOptions, clientOptions).start(); 
```

I think that clientOptions (of vscode-php-phan) can include Middleware, and if clientOptions.middleware.didSave is a no-op function (doesn't invoked passed in closure), didChange wouldn't get passed to the language server

Also see https://github.com/phan/phan/issues/1325

**Comment by adduc** [comment]
The latest release added the `phan.analyzeOnlyOnSave` setting, which resolves this issue.

Thanks!
