### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by hworld** [TysonAndre/vscode-php-phan#8]
After the analyze on save branch being merged in, it doesn't seem to be working. I tried enabling debugging in the settings, but it's no longer showing in the extension Output tab. In the processlist it's showing up, though. When I run Phan manually it works.

This commit works for me just fine: 12b8bdda20d47fa0958f8eafdc2169c5d48af39a
After that it's broken.

In master this is what shows up for "phan" in my processlist:
`php /home/ddecarmine/.vscode/extensions/TysonAndre.php-phan-0.0.9/vendor/phan/phan/phan --language-server-verbose --language-server-analyze-only-on-save --use-fallback-parser --language-server-tcp-connect=127.0.0.1:34873`

Not sure how to help debug this. =\

**Comment by TysonAndre** [comment]
Could you post the output of `php-config` and `php -m` for the php installation being used?

It could be that TCP sockets aren't supported, or some other issue (failing to be non-blockinh, not working as intended due to fork(), etc.

**Comment by TysonAndre** [comment]
What OS and OS version are you using. What repo did you use for downloading PHP binaries and extensions?

**Comment by TysonAndre** [comment]
Also, what version of VS Code are you using? I'm using php 7.2.2 with VS Code 1.20.0.

"Help > Toggle Developer Tools" might bring up useful information or the debugging logs in the console (Similar to Google Chrome developer tools for javascript) (e.g. Right click and "Save as" and copy that to a gist)

Unlikely: If you're running php in docker or a virtualized environment, it wouldn't work.

**Comment by TysonAndre** [comment]
https://ask.fedoraproject.org/en/question/9294/apache-php-sockets-not-working/

I've also seen turning off SELinux as a suggestion for fedora. Maybe PHP can't connect to arbitrary localhost TCP ports?

Will work on re-enabling the option to use stdin in the extension and adding a quick script to check if PHP cli can create and use sockets asynchronously

**Comment by TysonAndre** [comment]
1. Upgrade to vscode-php-phan 0.0.10. Does the issue still happen?
2. After upgrading to 0.0.10, add `phan.connectToServerWithStdio: true,` to the project's configuration. If the problem was caused by using TCP instead of STDIO, that should fix it.

Also, mentioned earlier:

> "Help > Toggle Developer Tools" might bring up useful information or the debugging logs in the console (Similar to Google Chrome developer tools for javascript) (e.g. Right click and "Save as" and copy that to a gist)


Other possible causes:

- A bug caused by explicitly including didOpen, etc. in the supported language server capabilities.
- Upgrading composer/npm dependencies

**Comment by hworld** [comment]
It seems that was the issue! stdin works, the sockets don't. Flipping the option between on/off reproduces it. I have SELinux off, so that shouldn't be the issue. I wonder if the firewall is blocking even locally...

**Comment by hworld** [comment]
Tried disabling firewalld and same issue... I can try to keep digging in to see if errors crop up anywhere. Will report back here if I find anything in the future.
